/*
* This file was generated by a tool.
* Rerun sql-ts to regenerate this file.
*/
export interface ActiveRoundEntity {
  "activeRound": number | null  // int4
}
export interface AnswerEntity {
  "id": number  // int4
  "roundQuestionId": string | null  // uuid
  "userId": string | null  // uuid
  "answer": Record<string, unknown>  // jsonb
}
export interface QuestionEntity {
  "id": number  // int4
  "text": string  // text
  "type": question_type  // question_type
  "options": Record<string, unknown>  // jsonb
  "answer": Record<string, unknown>  // jsonb
  "source": string | null  // uuid
}
export interface RoundEntity {
  "id": number  // int4
  "name": string  // text
  "description": string  // text
}
export interface RoundsQuestionEntity {
  "id"?: string  // uuid
  "questionId": number  // int4
  "roundId": number  // int4
  "startDate": Date | null  // timestamptz
  "endDate": Date | null  // timestamptz
  "active": boolean  // bool
}
export interface RoundsQuestionsNotificationEntity {
  "id": number  // int4
  "roundsQuestionsId": string  // uuid
  "notified": boolean  // bool
}
export interface RoundsQuestionsSlackNotificationEntity {
  "id": number  // int4
  "roundsQuestionsId": string  // uuid
  "slackChannel": string  // text
  "slackTs": string  // text
}
export interface SourceEntity {
  "id"?: string  // uuid
  "name": string  // text
}
export interface UserEntity {
  "id"?: string  // uuid
  "createdAt"?: Date  // timestamptz
}
export interface UsersSlackNotificationEntity {
  "id": string  // text
  "userId": string  // uuid
}
export enum question_type {
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  MULTIPLE_RESPONSE = "MULTIPLE_RESPONSE",
}
